version: "3.9"

services:
  backend:
    build: ./backend
    container_name: veritas-backend
    env_file:
      - ./backend/.env
    ports:
      - "8008:8008"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    container_name: veritas-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8008
    restart: always
